export const PROTOCOL_VERSION = 11 as const;
export const SCHEMA_VERSION = 16 as const;
export const APP_ID = "com.pi-desktop.app";
export const APP_NAME = "PI-Desktop";
export const APP_VERSION = "0.14.8";

export const APP_MENU_COMMANDS = [
  "newTask",
  "openProject",
  "openSettings",
  "openSearch",
  "openCommandPalette",
  "toggleSidebar",
  "openHelp",
  "openLogs",
  "checkForUpdates",
] as const;

export type AppMenuCommand = (typeof APP_MENU_COMMANDS)[number];

export const NATIVE_MENU_ACTIONS = [
  "undo",
  "redo",
  "cut",
  "copy",
  "paste",
  "selectAll",
  "reload",
  "zoomIn",
  "zoomOut",
  "resetZoom",
  "toggleFullScreen",
  "minimize",
  "toggleMaximize",
  "close",
  "restoreMainWindow",
] as const;

export type NativeMenuAction = (typeof NATIVE_MENU_ACTIONS)[number];

export const WINDOW_CONTROL_ACTIONS = [
  "getState",
  "minimize",
  "toggleMaximize",
  "close",
] as const;

export type WindowControlAction = (typeof WINDOW_CONTROL_ACTIONS)[number];

export const IPC = {
  invoke: {
    appGetVersion: "pi-desktop/app/getVersion",
    appOpenFeedback: "pi-desktop/app/openFeedback",
    appHealth: "pi-desktop/app/health",
    appGetOnboarding: "pi-desktop/app/getOnboarding",
    appDismissOnboarding: "pi-desktop/app/dismissOnboarding",
    /** Installed system font families, resolved by Electron main. */
    systemFontsList: "pi-desktop/app/systemFonts",
    updatesGetState: "pi-desktop/updates/getState",
    updatesCheck: "pi-desktop/updates/check",
    updatesDownload: "pi-desktop/updates/download",
    updatesInstall: "pi-desktop/updates/install",
    updatesOpenReleases: "pi-desktop/updates/openReleases",
    notificationList: "pi-desktop/notification/list",
    notificationMarkRead: "pi-desktop/notification/markRead",
    notificationMarkAllRead: "pi-desktop/notification/markAllRead",
    notificationClear: "pi-desktop/notification/clear",
    notificationShowNative: "pi-desktop/notification/showNative",
    notificationSetViewingSession: "pi-desktop/notification/setViewingSession",
    agentPrompt: "pi-desktop/agent/prompt",
    agentSteer: "pi-desktop/agent/steer",
    promptEnhance: "pi-desktop/prompt/enhance",
    agentCompact: "pi-desktop/agent/compact",
    agentAbort: "pi-desktop/agent/abort",
    agentStop: "pi-desktop/agent/stop",
    agentQueuePush: "pi-desktop/agent/queue/push",
    agentQueueList: "pi-desktop/agent/queue/list",
    agentQueueRemove: "pi-desktop/agent/queue/remove",
    agentQueuePrioritize: "pi-desktop/agent/queue/prioritize",
    agentGetStatus: "pi-desktop/agent/getStatus",
    agentInstructionsGet: "pi-desktop/agent/instructions/get",
    agentInstructionsSave: "pi-desktop/agent/instructions/save",
    sessionList: "pi-desktop/session/list",
    sessionCreate: "pi-desktop/session/create",
    sessionFork: "pi-desktop/session/fork",
    sessionMoveProject: "pi-desktop/session/moveProject",
    sessionGet: "pi-desktop/session/get",
    sessionCollaboration: "pi-desktop/session/collaboration",
    /** Validate and select a durable session from a reviewed host operation. */
    sessionOpen: "pi-desktop/session/open",
    sessionDelete: "pi-desktop/session/delete",
    sessionRename: "pi-desktop/session/rename",
    sessionSummarizeTitle: "pi-desktop/session/summarizeTitle",
    sessionConfigure: "pi-desktop/session/configure",
    sessionImportScan: "pi-desktop/session/importScan",
    sessionImportRun: "pi-desktop/session/importRun",
    modelConfigImportScan: "pi-desktop/modelConfig/importScan",
    modelConfigImportRun: "pi-desktop/modelConfig/importRun",
    sessionReplaceMessages: "pi-desktop/session/replaceMessages",
    sessionSaveRevision: "pi-desktop/session/saveRevision",
    sessionListRevisions: "pi-desktop/session/listRevisions",
    sessionActivateRevision: "pi-desktop/session/activateRevision",
    sessionGetScratchPath: "pi-desktop/session/getScratchPath",
    sessionOpenScratchPath: "pi-desktop/session/openScratchPath",
    projectOpenFolder: "pi-desktop/project/openFolder",
    settingsGet: "pi-desktop/settings/get",
    settingsSet: "pi-desktop/settings/set",
    networkProxyTest: "pi-desktop/network/testProxy",
    commandShellList: "pi-desktop/commandShell/list",
    secretsSet: "pi-desktop/secrets/set",
    secretsDelete: "pi-desktop/secrets/delete",
    secretsHas: "pi-desktop/secrets/has",
    projectOpen: "pi-desktop/project/open",
    projectPickFolders: "pi-desktop/project/pickFolders",
    projectMemoryGet: "pi-desktop/project/memory/get",
    projectMemorySave: "pi-desktop/project/memory/save",
    projectGroupList: "pi-desktop/project-group/list",
    projectGroupCreate: "pi-desktop/project-group/create",
    projectGroupRename: "pi-desktop/project-group/rename",
    projectGroupUpdate: "pi-desktop/project-group/update",
    projectGroupMemoryGet: "pi-desktop/project-group/memory/get",
    projectGroupMemorySave: "pi-desktop/project-group/memory/save",
    projectGroupInstructionsGet: "pi-desktop/project-group/instructions/get",
    projectGroupInstructionsSave: "pi-desktop/project-group/instructions/save",
    projectClone: "pi-desktop/project/clone",
    projectGet: "pi-desktop/project/get",
    projectList: "pi-desktop/project/list",
    projectSet: "pi-desktop/project/set",
    projectClear: "pi-desktop/project/clear",
    projectRemove: "pi-desktop/project/remove",
    pullsList: "pi-desktop/pulls/list",
    scheduledList: "pi-desktop/scheduled/list",
    scheduledCreate: "pi-desktop/scheduled/create",
    scheduledUpdate: "pi-desktop/scheduled/update",
    scheduledDelete: "pi-desktop/scheduled/delete",
    scheduledRun: "pi-desktop/scheduled/run",
    toolResolvePermission: "pi-desktop/tool/resolvePermission",
    askToolResolve: "pi-desktop/agent/askTool/resolve",
    plansPending: "pi-desktop/plans/pending",
    plansResolve: "pi-desktop/plans/resolve",
    providersList: "pi-desktop/providers/list",
    providersCreate: "pi-desktop/providers/create",
    providersUpdate: "pi-desktop/providers/update",
    providersDelete: "pi-desktop/providers/delete",
    providersTest: "pi-desktop/providers/testConnection",
    providersListModels: "pi-desktop/providers/listModels",
    providersRefreshModelCatalog: "pi-desktop/providers/refreshModelCatalog",
    providersModelCatalogStatus: "pi-desktop/providers/modelCatalogStatus",
    providersOauthVendors: "pi-desktop/providers/oauth/vendors",
    providersOauthStart: "pi-desktop/providers/oauth/start",
    providersOauthRespond: "pi-desktop/providers/oauth/respond",
    providersOauthCancel: "pi-desktop/providers/oauth/cancel",
    providersOauthDelete: "pi-desktop/providers/oauth/delete",
    pluginList: "pi-desktop/plugin/list",
    /** Plugin-contributed agent extensions (D387/D388, ADR 0214). */
    pluginImportExtension: "pi-desktop/plugin/importExtension",
    extensionsCommandRun: "pi-desktop/extensions/commands/run",
    extensionsUiRespond: "pi-desktop/extensions/ui/respond",
    pluginLoadDev: "pi-desktop/plugin/loadDev",
    pluginReload: "pi-desktop/plugin/reload",
    pluginCreateFromTemplate: "pi-desktop/plugin/createFromTemplate",
    pluginInstallFromPath: "pi-desktop/plugin/installFromPath",
    pluginInstallFromPackage: "pi-desktop/plugin/installFromPackage",
    pluginEnable: "pi-desktop/plugin/enable",
    pluginDisable: "pi-desktop/plugin/disable",
    pluginSetScope: "pi-desktop/plugin/setScope",
    pluginUninstall: "pi-desktop/plugin/uninstall",
    pluginSetAutoUpdate: "pi-desktop/plugin/setAutoUpdate",
    pluginSettingsGet: "pi-desktop/plugin/settings/get",
    pluginSettingsSet: "pi-desktop/plugin/settings/set",
    pluginOpenPanel: "pi-desktop/plugin/openPanel",
    pluginLauncherToggle: "pi-desktop/pluginLauncher/toggle",
    pluginLauncherDismiss: "pi-desktop/pluginLauncher/dismiss",
    pluginThemes: "pi-desktop/plugin/themes",
    pluginServices: "pi-desktop/plugin/services",
    pluginViews: "pi-desktop/plugin/views",
    pluginViewOpen: "pi-desktop/plugin/view/open",
    pluginViewClose: "pi-desktop/plugin/view/close",
    pluginViewSetBounds: "pi-desktop/plugin/view/setBounds",
    pluginViewSetVisible: "pi-desktop/plugin/view/setVisible",
    mcpList: "pi-desktop/mcp/list",
    mcpUpsert: "pi-desktop/mcp/upsert",
    mcpRemove: "pi-desktop/mcp/remove",
    mcpSetEnabled: "pi-desktop/mcp/setEnabled",
    mcpSetScope: "pi-desktop/mcp/setScope",
    mcpTest: "pi-desktop/mcp/test",
    mcpImport: "pi-desktop/mcp/import",
    mcpMarketSearch: "pi-desktop/mcp/market/search",
    skillList: "pi-desktop/skill/list",
    skillCreate: "pi-desktop/skill/create",
    skillImport: "pi-desktop/skill/import",
    skillMarketSearch: "pi-desktop/skill/market/search",
    skillMarketFetch: "pi-desktop/skill/market/fetch",
    skillUpdate: "pi-desktop/skill/update",
    skillRemove: "pi-desktop/skill/remove",
    skillSetEnabled: "pi-desktop/skill/setEnabled",
    skillSetScope: "pi-desktop/skill/setScope",
    skillRead: "pi-desktop/skill/read",
    skillReveal: "pi-desktop/skill/reveal",
    subagentList: "pi-desktop/subagent/list",
    subagentCatalog: "pi-desktop/subagent/catalog",
    subagentCreate: "pi-desktop/subagent/create",
    subagentUpdate: "pi-desktop/subagent/update",
    subagentRead: "pi-desktop/subagent/read",
    subagentRemove: "pi-desktop/subagent/remove",
    subagentSetEnabled: "pi-desktop/subagent/setEnabled",
    subagentSetScope: "pi-desktop/subagent/setScope",
    subagentReveal: "pi-desktop/subagent/reveal",
    marketRefresh: "pi-desktop/market/refresh",
    marketSearch: "pi-desktop/market/search",
    marketGetDetail: "pi-desktop/market/getDetail",
    marketInstall: "pi-desktop/market/install",
    marketCheckUpdates: "pi-desktop/market/checkUpdates",
    marketApplyUpdates: "pi-desktop/market/applyUpdates",
    commandPaletteSearch: "pi-desktop/commandPalette/search",
    commandPaletteExecute: "pi-desktop/commandPalette/execute",
    logOpenFolder: "pi-desktop/log/openFolder",
    devtoolsToggle: "pi-desktop/devtools/toggle",
    composerPickFiles: "pi-desktop/composer/pickFiles",
    composerPickPhotos: "pi-desktop/composer/pickPhotos",
    composerImportFiles: "pi-desktop/composer/importFiles",
    composerPasteFiles: "pi-desktop/composer/pasteFiles",
    clipboardRecordPaste: "pi-desktop/clipboard/recordPaste",
    composerCommands: "pi-desktop/composer/commands",
    workspaceDiff: "pi-desktop/workspace/diff",
    workspaceReviewRollback: "pi-desktop/workspace/review/rollback",
    browserNavigate: "pi-desktop/browser/navigate",
    browserAction: "pi-desktop/browser/action",
    browserSetBounds: "pi-desktop/browser/setBounds",
    browserSetVisible: "pi-desktop/browser/setVisible",
    browserOpenExternal: "pi-desktop/browser/openExternal",
    browserGetState: "pi-desktop/browser/getState",
    fsList: "pi-desktop/fs/list",
    fsRead: "pi-desktop/fs/read",
    fsReadImageDataUrl: "pi-desktop/fs/readImageDataUrl",
    statsGetTokenUsageHistory: "pi-desktop/stats/getTokenUsageHistory",
    fsReveal: "pi-desktop/fs/reveal",
    fsOpen: "pi-desktop/fs/open",
    fsIndex: "pi-desktop/fs/index",
    windowSetWorkPanelReservation:
      "pi-desktop/window/setWorkPanelReservation",
    windowSetWorkPanelChatWidth: "pi-desktop/window/setWorkPanelChatWidth",
    windowSetBackgroundColor: "pi-desktop/window/setBackgroundColor",
    windowControl: "pi-desktop/window/control",
    closeBehaviorGet: "pi-desktop/window/closeBehavior/get",
    closeBehaviorSet: "pi-desktop/window/closeBehavior/set",
    menuRendererReady: "pi-desktop/menu/rendererReady",
    nativeMenuAction: "pi-desktop/menu/nativeAction",
  },
  event: {
    pluginChanged: "pi-desktop/event/pluginChanged",
    /** Host-originated app settings mutation (e.g. plugin `app.setTheme`). */
    settingsChanged: "pi-desktop/app/event/settingsChanged",
    extensionsUiPrompt: "pi-desktop/extensions/event/uiPrompt",
    extensionsStatus: "pi-desktop/extensions/event/status",
    pluginLauncherShown: "pi-desktop/pluginLauncher/event/shown",
    agentMessage: "pi-desktop/agent/event/message",
    agentQueueChanged: "pi-desktop/agent/event/queueChanged",
    hostStatus: "pi-desktop/app/event/hostStatus",
    toast: "pi-desktop/app/event/toast",
    browserState: "pi-desktop/browser/event/state",
    browserPreview: "pi-desktop/browser/event/preview",
    windowMaximized: "pi-desktop/window/event/maximized",
    windowFullScreen: "pi-desktop/window/event/fullscreen",
    windowWorkPanelResize: "pi-desktop/window/event/workPanelResize",
    menuCommand: "pi-desktop/menu/event/command",
    notificationChanged: "pi-desktop/notification/event/changed",
    sessionsChanged: "pi-desktop/session/event/changed",
    notificationActivated: "pi-desktop/notification/event/activated",
    plansChanged: "pi-desktop/plans/event/changed",
    providersOauth: "pi-desktop/providers/oauth/event",
    updatesState: "pi-desktop/updates/event/state",
  },
} as const;

export const IPC_WHITELIST = new Set<string>([
  ...Object.values(IPC.invoke),
  ...Object.values(IPC.event),
]);
